### ISSUE TITLE
cann't run

### ISSUE THREAD

**Issue by hanbim520** [iFunFactory/engine-plugin-ue4#1]
I want to try to run this pro,but something wrong with it.
Like the pic
![1 2](https://cloud.githubusercontent.com/assets/7490792/14013446/8b63c422-f1e7-11e5-835c-57efa3be1141.png)

my unreal engine version is 4.10
I need use protobuf, can u help me?

Supplementary information：
Could protobuf be used on blueprint? I need this function

**Comment by junhyun-ifunfactory** [comment]
text encoding issue

do not download zip file
use github desktop 
clone project

or

Run visual studio 2015
funapi_tester.cpp -> File Menu -> Advanced Save Options -> Unicode (Big-Endian) - Codepage 1201

![00](https://cloud.githubusercontent.com/assets/14173097/14035440/8d02c2c6-f271-11e5-9e74-1902ddbe4191.png)

and 

not yet supported "protobuf be used on blueprint"
I will find the solution

Thank you for your comment

**Comment by hanbim520** [comment]
En,I make a structure for proto file on blueprint or c++,and it works. I don't know how to use property class to provide for blueprint from cpp but element type like int,bool,float.
but i think it's too trouble by using this method。I want to find a method like protobuf-lua to solute it so that it can be used in the blueprint directly.

**Comment by DeepNori** [comment]
Hi hanbim520,

I think you are asking how to integrate protobuf into the Blueprint.
I'm sorry but I'm also trying to figure it out.
I will let you know if I find how.
Thanks.

**Comment by hanbim520** [comment]
Sorry for my bad english.
I do like this
![1](https://cloud.githubusercontent.com/assets/7490792/14164710/7e815a38-f734-11e5-8d51-9c65834fd52d.png)
![2](https://cloud.githubusercontent.com/assets/7490792/14164713/827f9f6e-f734-11e5-8943-a8fc76029c56.png)
![3](https://cloud.githubusercontent.com/assets/7490792/14164779/30b3db22-f735-11e5-978a-546f6d91367f.png)
![6](https://cloud.githubusercontent.com/assets/7490792/14164988/14a4b382-f737-11e5-80bc-46a570d908af.png)
![4](https://cloud.githubusercontent.com/assets/7490792/14164912/66172052-f736-11e5-909c-0f24046a3a43.png)

![5](https://cloud.githubusercontent.com/assets/7490792/14164891/3d9c71cc-f736-11e5-94be-cd726d15ee85.png)

I tranlate proto to unreal-C++ language and BP structure,and it works in Bp from c++.But this method is too trouble,I want to fulfill protobuf-unreal so that it can be used in BP directly
